version: '3'
services:
    backend:
        environment:
        - LOCAL=1
        - FLASK_ENV=development
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
